version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
      time: "14:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10
