version: 2.1

orbs:
  node: circleci/node@4

jobs:
  lint:
    executor:
      name: node/default
      tag: "10.22"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint
  unit_tests:
    executor:
      name: node/default
      tag: "10.22"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: yarn test
          command: yarn test:coverage --ci --color --reporters=default --reporters=jest-junit --runInBand
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./tmp/test-results
            JEST_JUNIT_OUTPUT_NAME: jest.xml
      - store_test_results:
          path: ./tmp/test-results

workflows:
  build:
    jobs:
      - lint
      - unit_tests
