version: 2.1
orbs:
  node: circleci/node@1.1.6

jobs:
  lint:
    executor:
      name: node/default
      tag: "8"
    steps:
      - checkout
      - node/with-cache:
          steps:
          - run: yarn install
          - run: yarn lint
  unit_tests:
    executor:
      name: node/default
      tag: "8"
    steps:
      - checkout
      - node/with-cache:
          steps:
          - run: yarn install
          - run:
              name: yarn test
              command: yarn test:coverage --ci --color --reporters=default --reporters=jest-junit --runInBand
              environment:
                JEST_JUNIT_OUTPUT_DIR: ./tmp/test-results
                JEST_JUNIT_OUTPUT_NAME: jest.xml
          - store_test_results:
              path: ./tmp/test-results

workflows:
  version: 2
  build:
    jobs:
      - lint
      - unit_tests
