version: 2.1
orbs:
  node: circleci/node@4.4.0

executors:
  node:
    docker:
      - image: cimg/node:16.13.0

commands:
  install-dependencies:
    description: Install dependencies
    steps:
      - node/install-packages:
          pkg-manager: yarn

jobs:
  install_deps:
    executor: node
    steps:
      - checkout
      - install-dependencies
  lint:
    executor: node
    steps:
      - checkout
      - install-dependencies
      - run: yarn lint
  unit_tests:
    executor: node
    steps:
      - checkout
      - install-dependencies
      - run:
          name: yarn test
          command: yarn test:coverage --ci --color --reporters=default --reporters=jest-junit --runInBand
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./tmp/test-results
            JEST_JUNIT_OUTPUT_NAME: jest.xml
      - store_test_results:
          path: ./tmp/test-results

workflows:
  version: 2
  build:
    jobs:
      - install_deps
      - lint:
          requires:
            - install_deps
      - unit_tests:
          requires:
            - install_deps
